"""Deterministic relay of specialist-generated infrastructure-as-code.

Specialists are tools of the orchestrator, so their text reaches the user only
through the orchestrator's own final answer. For prose that is fine; for a
CloudFormation or Terraform template it is not. The orchestrator re-types (and
under its token budget, truncates or paraphrases) the template, so the user can
end up with IaC that does not match what the specialist produced, or with only a
description of a template that was never shown.

This module treats the specialist's fenced IaC blocks as the authoritative
artifact. On the non-cost path the orchestrator keeps its prose, any IaC-looking
blocks it re-typed are removed, and the specialist's original blocks are
appended verbatim (subject to bounds and the financial fail-closed check).

Relayed text is unmodified model output that already passed the Bedrock
guardrail on the specialist's call; nothing here broadens what the runtime can
do. It stays a read-only assistant and the appended notice says so.
"""

# Standard library
import re
from typing import Iterable

# Local modules
from agents.financial_guard import contains_unvalidated_financial_content

# Fence tokens we consider IaC-capable. Filename-style tokens (template.yaml,
# main.tf) are reduced to their extension.
_IAC_LANGUAGES = frozenset({"yaml", "yml", "json", "hcl", "tf", "terraform"})

# Content markers that distinguish infrastructure templates from ordinary YAML
# or JSON snippets (e.g. a Kubernetes label example or an API response).
_IAC_MARKERS = re.compile(
    r"AWSTemplateFormatVersion"
    r"|^\s*Resources\s*:"
    r'|"Resources"\s*:'
    r"|^\s*Type\s*:\s*['\"]?AWS::"
    r'|"Type"\s*:\s*"AWS::'
    r'|^\s*resource\s+"aws_',
    re.MULTILINE,
)

# A complete fenced block: opening fence with a token, body, closing fence on
# its own line. Unterminated fences (a truncated template) never match, so a
# partial template is never presented as a deployable artifact.
_FENCED_BLOCK = re.compile(
    r"^(?P<fence>`{3,})(?P<token>[\w.+-]+)[ \t]*\n(?P<body>.*?)^(?P=fence)[ \t]*$",
    re.MULTILINE | re.DOTALL,
)

# Bounds (code-owned, like the provider projections): never relay an unbounded
# amount of model output.
MAX_RELAYED_BLOCKS = 3
MAX_BLOCK_CHARS = 60_000

# Only operational specialists' IaC is relayed. Cost output has its own
# authoritative rendering path and is never relayed from model prose.
_RELAY_SERVICES = frozenset({"gamelift", "eks"})

RELAY_HEADING = "## Generated infrastructure as code"
RELAY_NOTICE = (
    "The template below was generated by the {service} specialist and is shown exactly as produced. "
    "This assistant is read-only and has not created any resources. Review the template, validate it "
    "(for example with `aws cloudformation validate-template`), and deploy it yourself."
)


def _language(token: str) -> str:
    token = token.lower()
    return token.rsplit(".", 1)[-1] if "." in token else token


def _is_iac_block(token: str, body: str) -> bool:
    return _language(token) in _IAC_LANGUAGES and bool(_IAC_MARKERS.search(body))


def extract_iac_blocks(text: str) -> list[str]:
    """Return complete fenced IaC blocks from ``text``, in order, bounded.

    Each item is the full fenced block (fences included) so the UI keeps its
    language token, highlighting, and download filename.
    """
    if not text:
        return []
    blocks: list[str] = []
    for match in _FENCED_BLOCK.finditer(text):
        if not _is_iac_block(match.group("token"), match.group("body")):
            continue
        block = match.group(0)
        if len(block) > MAX_BLOCK_CHARS:
            continue
        blocks.append(block)
        if len(blocks) >= MAX_RELAYED_BLOCKS:
            break
    return blocks


def strip_iac_blocks(text: str) -> str:
    """Remove IaC-looking fenced blocks (re-typed copies) from ``text``."""
    if not text:
        return text

    def _drop(match: re.Match[str]) -> str:
        return "" if _is_iac_block(match.group("token"), match.group("body")) else match.group(0)

    stripped = _FENCED_BLOCK.sub(_drop, text)
    return re.sub(r"\n{3,}", "\n\n", stripped).strip()


def relay_specialist_iac(response_text: str, specialist_outputs: Iterable[tuple[str, str]]) -> str:
    """Append specialist IaC blocks verbatim to the orchestrator's answer.

    Returns ``response_text`` unchanged when no relayable IaC exists. Blocks that
    carry unvalidated financial content are dropped (fail closed), matching the
    rule that only the cost report may present monetary values.
    """
    sections: list[str] = []
    relayed = 0
    for service_name, output in specialist_outputs:
        normalized = (service_name or "").strip().lower()
        if normalized not in _RELAY_SERVICES or not output:
            continue
        blocks = [b for b in extract_iac_blocks(output) if not contains_unvalidated_financial_content(b)]
        blocks = blocks[: max(0, MAX_RELAYED_BLOCKS - relayed)]
        if not blocks:
            continue
        relayed += len(blocks)
        display = service_name.strip() or "specialist"
        sections.append("\n\n".join([RELAY_NOTICE.format(service=display), *blocks]))
        if relayed >= MAX_RELAYED_BLOCKS:
            break

    if not sections:
        return response_text

    prose = strip_iac_blocks(response_text or "")
    parts = [prose] if prose else []
    parts.append(RELAY_HEADING)
    parts.extend(sections)
    return "\n\n".join(parts)
