"""Deterministic relay of specialist-generated infrastructure-as-code.

Specialists are tools of the orchestrator, so their text reaches the user only
through the orchestrator's own final answer. For prose that is fine; for a
CloudFormation or Terraform template it is not. The orchestrator re-types (and
under its token budget, truncates or paraphrases) the template, so the user can
end up with IaC that does not match what the specialist produced, or with only a
description of a template that was never shown.

This module treats the specialist's fenced IaC blocks as the authoritative
artifact. On the non-cost path the orchestrator keeps its prose, any IaC-looking
blocks it re-typed are removed, and the specialist's original blocks are
appended verbatim (subject to bounds and the financial fail-closed check).

Relayed text is unmodified model output that already passed the Bedrock
guardrail on the specialist's call; nothing here broadens what the runtime can
do. It stays a read-only assistant and the appended notice says so.
"""

# Standard library
import re
from typing import Iterable

# Local modules
from agents.cfn_template_validation import GUARDRAIL_PLACEHOLDER_RE
from agents.financial_guard import contains_unvalidated_financial_content

# Fence tokens we consider IaC-capable. Filename-style tokens (template.yaml,
# main.tf) are reduced to their extension.
_IAC_LANGUAGES = frozenset({"yaml", "yml", "json", "hcl", "tf", "terraform"})

# Content markers that distinguish infrastructure templates from ordinary YAML
# or JSON snippets (e.g. a Kubernetes label example or an API response).
_IAC_MARKERS = re.compile(
    r"AWSTemplateFormatVersion"
    r"|^\s*Resources\s*:"
    r'|"Resources"\s*:'
    r"|^\s*Type\s*:\s*['\"]?AWS::"
    r'|"Type"\s*:\s*"AWS::'
    r'|^\s*resource\s+"aws_',
    re.MULTILINE,
)

# A complete fenced block: opening fence with a token, body, closing fence on
# its own line. Unterminated fences (a truncated template) never match, so a
# partial template is never presented as a deployable artifact.
_FENCED_BLOCK = re.compile(
    r"^(?P<fence>`{3,})(?P<token>[\w.+-]+)[ \t]*\n(?P<body>.*?)^(?P=fence)[ \t]*$",
    re.MULTILINE | re.DOTALL,
)

# Bounds (code-owned, like the provider projections): never relay an unbounded
# amount of model output.
# All limits are UTF-8 bytes and apply to what is actually emitted.
MAX_RELAYED_BLOCKS = 3
MAX_BLOCK_BYTES = 56_000  # a 51,200-byte TemplateBody plus its fence and language token
MAX_RELAYED_ANSWER_BYTES = 80_000
MAX_RELAYED_TOTAL_BYTES = 120_000  # the whole emitted section: heading, notices, answers, blocks
MAX_PROSE_BYTES = 8_000  # the routing model's overview kept above the relayed section


def _size(text: str) -> int:
    return len(text.encode("utf-8"))


# Only operational specialists' IaC is relayed. Cost output has its own
# authoritative rendering path and is never relayed from model prose.
_RELAY_SERVICES = frozenset({"gamelift", "eks"})

RELAY_HEADING = "## Generated infrastructure as code"
WITHHELD_NOTICE = (
    "The {service} specialist generated an infrastructure-as-code template, but it was withheld "
    "because it contained a monetary value that did not come from the validated cost report. "
    "Ask again and request that any cost or price inputs be template parameters."
)
RELAY_NOTICE = (
    "The {subject} below is an untrusted draft generated by the {service} specialist, shown exactly as "
    "produced. This assistant is read-only and has not created, changed, or deployed any resources. Any "
    "validation it reports covers only the checks it names. Review the template, validate it yourself "
    "(for example with `aws cloudformation validate-template`), and decide whether to deploy it."
)
MASKED_VALUES_NOTICE = (
    "The content filter masked {count} value(s) in the template above (shown as placeholders such as "
    "{example}). The template will not deploy until you replace them with your own values or parameters."
)
UNSOURCED_IAC_NOTICE = (
    "An infrastructure-as-code template in this answer was removed because no specialist produced or "
    "validated it. Ask again for the template on its own."
)
TRUNCATED_NOTICE = (
    "Some generated content was not shown because the answer exceeded the relay size limit. "
    "Ask for one template at a time."
)


def _language(token: str) -> str:
    token = token.lower()
    return token.rsplit(".", 1)[-1] if "." in token else token


def _is_iac_block(token: str, body: str) -> bool:
    return _language(token) in _IAC_LANGUAGES and bool(_IAC_MARKERS.search(body))


def extract_iac_blocks(text: str) -> list[str]:
    """Return complete fenced IaC blocks from ``text``, in order, bounded.

    Each item is the full fenced block (fences included) so the UI keeps its
    language token, highlighting, and download filename.
    """
    if not text:
        return []
    blocks: list[str] = []
    for match in _FENCED_BLOCK.finditer(text):
        if not _is_iac_block(match.group("token"), match.group("body")):
            continue
        block = match.group(0)
        if _size(block) > MAX_BLOCK_BYTES:
            continue
        blocks.append(block)
        if len(blocks) >= MAX_RELAYED_BLOCKS:
            break
    return blocks


def strip_iac_blocks(text: str) -> str:
    """Remove IaC-looking fenced blocks (re-typed copies) from ``text``."""
    if not text:
        return text

    def _drop(match: re.Match[str]) -> str:
        return "" if _is_iac_block(match.group("token"), match.group("body")) else match.group(0)

    stripped = _FENCED_BLOCK.sub(_drop, text)
    return re.sub(r"\n{3,}", "\n\n", stripped).strip()


def relay_specialist_iac(response_text: str, specialist_outputs: Iterable[tuple[str, str]]) -> str:
    """Append a specialist's IaC answer verbatim to the orchestrator's answer.

    When a specialist answer contains complete IaC blocks and the whole answer is
    financially clean and within bounds, the full answer (plan, template, and
    cutover steps) is relayed so the routing model only needs a short overview.
    Otherwise only the IaC blocks are relayed. Blocks that carry unvalidated
    financial content are dropped (fail closed), matching the rule that only the
    cost report may present monetary values. ``specialist_outputs`` is in call
    order and may repeat a service; at most one answer per service is relayed
    (the earliest with relayable IaC). Returns ``response_text`` unchanged when
    no relayable IaC exists.
    """
    sections: list[str] = []
    relayed = 0
    # One relayed answer per service. ``specialist_outputs`` may hold several
    # answers from the same specialist (the orchestrator can call it more than
    # once); the earliest answer with relayable IaC wins because it carries the
    # user's original requirements, while later calls are narrower follow-ups
    # whose templates (if any) were built from paraphrased inputs.
    relayed_services: set[str] = set()
    withheld_services: dict[str, str] = {}
    for service_name, output in specialist_outputs:
        normalized = (service_name or "").strip().lower()
        if normalized not in _RELAY_SERVICES or not output or normalized in relayed_services:
            continue
        display = service_name.strip() or "specialist"
        found = extract_iac_blocks(output)
        blocks = [b for b in found if not contains_unvalidated_financial_content(b)]
        blocks = blocks[: max(0, MAX_RELAYED_BLOCKS - relayed)]
        if not blocks:
            if found:
                # Remember the fail-closed outcome so it is made visible if no
                # other answer from this service can be relayed.
                withheld_services.setdefault(normalized, display)
            continue
        relayed_services.add(normalized)
        withheld_services.pop(normalized, None)
        relayed += len(blocks)
        answer = output.strip()
        if _size(answer) <= MAX_RELAYED_ANSWER_BYTES and not contains_unvalidated_financial_content(answer):
            entry = [RELAY_NOTICE.format(subject="answer", service=display), answer]
        else:
            entry = [RELAY_NOTICE.format(subject="template", service=display), *blocks]
        # The output guardrail can anonymize values (for example IP ranges)
        # after the specialist validated its draft. Say so next to the template.
        masked = [m.group(0) for block in blocks for m in GUARDRAIL_PLACEHOLDER_RE.finditer(block)]
        if masked:
            entry.append(MASKED_VALUES_NOTICE.format(count=len(masked), example=masked[0]))
        sections.append("\n\n".join(entry))
        if relayed >= MAX_RELAYED_BLOCKS:
            break

    # Make a fail-closed outcome visible instead of silently returning an answer
    # that refers to a template the user never sees.
    sections.extend(WITHHELD_NOTICE.format(service=display) for display in withheld_services.values())
    if not sections:
        if extract_iac_blocks(response_text or ""):
            # The routing model wrote infrastructure code itself (for example
            # after a specialist failed). No specialist produced or validated
            # it, so it is not shown as an artifact.
            prose = strip_iac_blocks(response_text or "")
            return "\n\n".join(part for part in (prose, UNSOURCED_IAC_NOTICE) if part)
        return response_text

    # Enforce the aggregate bound on the emitted payload. Sections are kept
    # whole (a fenced block is never cut) and in order; anything that does not
    # fit is dropped with a visible notice.
    emitted: list[str] = [RELAY_HEADING]
    budget = MAX_RELAYED_TOTAL_BYTES - _size(RELAY_HEADING) - _size(TRUNCATED_NOTICE) - 8
    dropped = False
    for section in sections:
        cost = _size(section) + 2
        if cost > budget:
            dropped = True
            continue
        emitted.append(section)
        budget -= cost
    if dropped:
        emitted.append(TRUNCATED_NOTICE)

    prose = strip_iac_blocks(response_text or "")
    if _size(prose) > MAX_PROSE_BYTES:
        prose = prose.encode("utf-8")[:MAX_PROSE_BYTES].decode("utf-8", errors="ignore").rstrip() + " …"
        if len(re.findall(r"^`{3,}", prose, re.MULTILINE)) % 2:
            # A cut inside a code fence would swallow the relayed section when rendered.
            prose += "\n```"
    return "\n\n".join([prose, *emitted] if prose else emitted)
