#!/usr/bin/env python3
"""Property-based test for successful proposal integrity (`connector.service.propose_change`).

Covers Correctness Property 10 from the source-control-connector design: whenever a
proposal succeeds, its externally observable outcome is complete and correct. For any
authorized request that reaches and completes the provider operations, the connector:

- opens **exactly one** pull request (Req 2.2),
- commits the **complete set** of proposed IaC files — every proposed path and its exact
  content appears in the recorded ``commit_files`` call (Req 2.3),
- returns a result carrying the pull-request **id and url** (Req 2.6), and
- includes in the PR body an **agent + user attribution** that references the requesting
  user, i.e. it states the proposal was generated by the agent on behalf of that user
  (Req 6.5).

The service is exercised with a ``FakeProvider`` injected via ``provider=`` (its default
behavior makes every proposal succeed and records each operation), an enabled
:class:`ConnectorConfig` injected via ``config=`` whose allowlist matches the requested
repository/branch, and ``connector.service.get_secret`` mocked so no AWS call occurs.
Identity is supplied through the request contextvar with an authorized ``user_id``.

The per-user rate limiter keeps state in a shared, module-level store
(``utils.security._rate_limit_windows``). To keep examples independent, that store is
cleared before each example and a unique ``user_id`` is used per example, so the rate-limit
gate never rejects a request under test.

Validates: Requirements 2.2, 2.3, 2.6, 6.5
"""

# Standard library
import itertools
import json
from unittest.mock import patch

# Third-party packages
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

# Local modules
from connector.config import AllowlistEntry, SourceControlConfig
from support.config_factory import make_source_control_config
from connector.models import ProposedFile
from connector.service import propose_change
from support.fake_provider import DEFAULT_HEAD_SHA, FakeProvider
from utils.request_context import reset_request_context, set_request_context
from utils.security import _rate_limit_windows

pytestmark = pytest.mark.unit


# --- Test constants --------------------------------------------------------

_REPO = "org/iac-repo"
_BRANCH = "main"
_GROUP = "scm-writers"
_IAC_FORMAT = "cloudformation"

# A small pool of benign words used to build varying, injection-free intents/titles so the
# input-validation and prompt-injection gates always pass and every request reaches the
# provider operations.
_SAFE_WORDS = [
    "update",
    "storage",
    "bucket",
    "queue",
    "configuration",
    "resource",
    "infrastructure",
    "template",
    "service",
    "stack",
    "memory",
    "scaling",
]

# CloudFormation resource types used to build structurally valid templates.
_RESOURCE_TYPES = [
    "AWS::S3::Bucket",
    "AWS::SQS::Queue",
    "AWS::SNS::Topic",
    "AWS::DynamoDB::Table",
    "AWS::Logs::LogGroup",
]

# Monotonic source of unique user ids so each example starts with a fresh rate-limit budget.
_user_ids = itertools.count(1)


def _make_config() -> SourceControlConfig:
    """Build an enabled ConnectorConfig whose allowlist matches the requested repo/branch."""
    return make_source_control_config(
        enabled=True,
        provider="github",
        credential_secret_id="scm/credential",
        allowlist=(AllowlistEntry(repo=_REPO, target_branches=(_BRANCH,)),),
        authorized_groups=(_GROUP,),
        rate_limit_max=1000,
        rate_limit_window_seconds=3600,
        provider_timeout_seconds=30,
        retry_max_attempts=3,
        max_files_per_request=20,
        provider_base_url=None,
        audit_log_group="scm-audit",
        config_errors=(),
    )


@st.composite
def _valid_cfn_files(draw):
    """Generate 1..N distinct, structurally valid CloudFormation ``ProposedFile``s.

    Each file has a unique path (index-suffixed) so the proposed set has no duplicate paths,
    and a JSON body (valid YAML too) with a non-empty ``Resources`` mapping whose single
    resource declares a ``Type`` — exactly what the IaC validation gate requires.
    """
    specs = draw(
        st.lists(
            st.tuples(
                st.from_regex(r"[A-Za-z][A-Za-z0-9]{2,15}", fullmatch=True),
                st.sampled_from(_RESOURCE_TYPES),
            ),
            min_size=1,
            max_size=5,
        )
    )
    files: list[ProposedFile] = []
    for index, (logical_id, resource_type) in enumerate(specs):
        template = {"Resources": {logical_id: {"Type": resource_type}}}
        files.append(
            ProposedFile(
                path=f"templates/resource_{index}.yaml",
                content=json.dumps(template),
                iac_format=_IAC_FORMAT,
            )
        )
    return files


# --- Property 10 -----------------------------------------------------------


# Feature: source-control-connector, Property 10: Successful proposal integrity
@settings(max_examples=100)
@given(
    files=_valid_cfn_files(),
    intent_words=st.lists(st.sampled_from(_SAFE_WORDS), min_size=2, max_size=6),
)
def test_property10_successful_proposal_integrity(files, intent_words):
    """A successful proposal opens one PR carrying every file, ids/url, and attribution.

    For any authorized request with a valid, non-empty CloudFormation file set that reaches
    the provider operations, the connector opens exactly one pull request (Req 2.2), commits
    the complete set of proposed files (Req 2.3), returns the PR id + url (Req 2.6), and the
    PR body attributes the proposal to the agent acting on behalf of the requesting user
    (Req 6.5).
    """
    # Isolate this example: clear the shared sliding-window store and use a fresh user id.
    _rate_limit_windows.clear()

    config = _make_config()
    provider = FakeProvider()

    user_id = f"user-{next(_user_ids)}"
    intent = " ".join(intent_words)
    title = f"Update {intent_words[0]} configuration"
    description = f"Adjust the {intent_words[-1]} in the infrastructure template."

    token = set_request_context({"user_id": user_id, "groups": [_GROUP], "session_id": "s-1"})
    try:
        # Credential acquisition is adapter-owned behind ProviderAuth; the core issues no
        # get_secret and the injected FakeProvider needs none, so no credential patch.
        result = propose_change(
            intent,
            files,
            _IAC_FORMAT,
            title,
            description,
            base_revision=DEFAULT_HEAD_SHA,
            config=config,
            provider=provider,
        )
    finally:
        reset_request_context(token)

    # The pipeline completed successfully.
    assert result.status == "created", result.message

    # Req 2.2: exactly one pull request was opened.
    pr_calls = provider.calls_for("open_change_proposal")
    assert len(pr_calls) == 1
    assert len(provider.pull_requests) == 1

    # Req 2.6: the result carries the PR id and url, matching the opened PR.
    assert result.proposal_id
    assert result.proposal_url
    opened_pr = provider.pull_requests[0]
    assert result.proposal_id == opened_pr["proposal_id"]
    assert result.proposal_url == opened_pr["proposal_url"]

    # Req 2.3: the commit carries the COMPLETE set of proposed files — every proposed path
    # and its exact content appears in the single recorded commit_files call.
    commit_calls = provider.calls_for("commit_files")
    assert len(commit_calls) == 1
    committed = commit_calls[0]["files"]
    committed_pairs = {(f.path, f.content) for f in committed}
    proposed_pairs = {(f.path, f.content) for f in files}
    assert committed_pairs == proposed_pairs
    # No file is dropped or duplicated: the counts line up with the proposed set.
    assert len(committed) == len(files)

    # Req 6.5: the PR body attributes the proposal to the agent on behalf of the requesting
    # user, referencing that specific user id.
    body = opened_pr["body"]
    assert user_id in body
    assert "on behalf of" in body.lower()
    assert "agent" in body.lower()

    # Defense-in-depth: the credential value never leaks into the agent-visible result.
    assert "ghp_fake_token_value" not in result.message
