#!/usr/bin/env python3
"""Property-based test for proposal-branch uniqueness and base-commit selection.

Covers Correctness Property 11 from the source-control-connector design: the proposal
branch the Connector creates is (a) *based on the latest commit* of the configured target
branch and (b) *uniquely named* — the Connector never issues a ``create_branch`` against a
name the provider already reports as existing.

``connector.service.propose_change`` runs its fail-closed pipeline and, on the provider
stage, reads ``latest_commit_sha`` for the matched target branch, then repeatedly generates
a candidate proposal-branch name and calls ``branch_exists`` until it finds a free name,
creating the branch only from that free name and from the latest target-commit SHA.

Two facets are proven across generated inputs:

- **Req 3.3 (base commit):** ``create_branch`` is called with ``from_sha`` equal to the
  exact ``latest_commit_sha`` the provider reported for the target branch. Different SHAs
  are generated by Hypothesis.
- **Req 2.1 / 2.8 (uniqueness):** ``branch_exists`` is programmed to report the first
  ``k`` generated candidates as already existing; the service regenerates until it finds a
  free name and calls ``create_branch`` exactly once, using a name that ``branch_exists``
  reported as *not* existing (never one of the colliding names). Different collision counts
  are generated by Hypothesis.

The service is exercised with a ``FakeProvider`` injected via ``provider=`` (programming
``latest_commit_sha`` / ``branch_exists``) and an enabled :class:`ConnectorConfig` injected
via ``config=``. An authorized user is placed in the request context, ``get_secret`` is
mocked, valid CloudFormation is proposed against an allowlist-matching repo/branch, and the
rate-limit gate (which sits before the provider stage) is neutralized so this test isolates
the branch-selection behavior. The request context is reset per example.

Validates: Requirements 2.1, 2.8, 3.3
"""

# Standard library
from unittest import mock

# Third-party packages
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

# Local modules
from connector.config import AllowlistEntry, SourceControlConfig
from support.config_factory import make_source_control_config
from connector.models import ProposedFile
from connector import service
from connector.service import propose_change
from support.fake_provider import FakeProvider
from utils.request_context import reset_request_context, set_request_context

pytestmark = pytest.mark.unit


# The single configured repository/branch the propose path defaults to (allowlist[0]);
# the request supplies no repo/branch so an authorized request lands an exact allowlist
# match and reaches the provider stage where the branch is selected and created.
_REPO = "org/iac-repo"
_BRANCH = "main"

# An authorized requesting user whose group intersects the configured authorized groups.
_AUTHORIZED_CONTEXT = {"user_id": "user-123", "groups": ["scm-writers"], "session_id": "s-1"}

# A structurally valid CloudFormation template (passes the IaC validation gate).
_VALID_CFN = '{"Resources": {"Bucket": {"Type": "AWS::S3::Bucket"}}}'

# The service regenerates a branch name at most this many times before giving up; keep the
# generated collision count strictly below it so a free name is always found.
_MAX_BRANCH_NAME_ATTEMPTS = service._MAX_BRANCH_NAME_ATTEMPTS


def _make_config() -> SourceControlConfig:
    """Build an enabled SourceControlConfig backed by a single-entry allowlist."""
    return make_source_control_config(
        enabled=True,
        provider="github",
        credential_secret_id="scm/credential",
        allowlist=(AllowlistEntry(repo=_REPO, target_branches=(_BRANCH,)),),
        authorized_groups=("scm-writers",),
        rate_limit_max=1000,
        rate_limit_window_seconds=3600,
        provider_timeout_seconds=30,
        retry_max_attempts=3,
        max_files_per_request=20,
        provider_base_url=None,
        audit_log_group="scm-audit",
        config_errors=(),
    )


def _proposed_files() -> list[ProposedFile]:
    return [ProposedFile(path="template.yaml", content=_VALID_CFN, iac_format="cloudformation")]


def _call_propose(fake: FakeProvider):
    """Invoke ``propose_change`` with an authorized user; credential + rate-limit neutralized."""
    token = set_request_context(dict(_AUTHORIZED_CONTEXT))
    try:
        with (
            mock.patch.object(service, "get_secret", return_value="ghs_faketoken1234567890abcd"),
            mock.patch.object(service, "check_rate_limit", return_value=None),
        ):
            return propose_change(
                intent="update the storage bucket configuration",
                files=_proposed_files(),
                iac_format="cloudformation",
                title="Update bucket configuration",
                description="Enable versioning on the storage bucket.",
                config=_make_config(),
                provider=fake,
            )
    finally:
        reset_request_context(token)


# Feature: source-control-connector, Property 11: Proposal branch is unique and based on the latest target commit
@settings(max_examples=100)
@given(
    latest_sha=st.from_regex(r"[0-9a-f]{7,40}", fullmatch=True),
    collisions=st.integers(min_value=0, max_value=_MAX_BRANCH_NAME_ATTEMPTS - 1),
)
def test_property11_branch_unique_and_based_on_latest_commit(latest_sha, collisions):
    """The proposal branch is created from the latest target-commit SHA and from a name the
    provider reports as free — never one it reports as already existing (Req 2.1, 2.8, 3.3)."""
    fake = FakeProvider()

    # (Req 3.3) The provider reports this as the latest commit of the target branch; the
    # service must base the proposal branch on exactly this SHA.
    fake.set_return("latest_commit_sha", latest_sha)

    # (Req 2.8) Report the first ``collisions`` generated candidate names as already
    # existing, then a free name; the service must regenerate until it finds the free one.
    fake.program("branch_exists", side_effects=[True] * collisions + [False])

    result = _call_propose(fake)

    # The pipeline reached and completed the provider stage: exactly one proposal created.
    assert result.status == "created", result.message
    assert result.proposal_id is not None

    # --- (Req 3.3) base commit ----------------------------------------------------------
    base_calls = fake.calls_for("latest_commit_sha")
    assert base_calls, "the service must read the latest commit of the target branch"
    assert base_calls[0]["repo"] == _REPO
    assert base_calls[0]["branch"] == _BRANCH

    create_calls = fake.calls_for("create_branch")
    assert len(create_calls) == 1, "exactly one branch must be created"
    create_call = create_calls[0]
    # The branch is created from the exact latest-commit SHA the provider reported (Req 3.3).
    assert create_call["from_sha"] == latest_sha
    assert create_call["repo"] == _REPO

    # --- (Req 2.1 / 2.8) uniqueness -----------------------------------------------------
    exists_calls = fake.calls_for("branch_exists")
    # One existence check per generated candidate: ``collisions`` colliding names, then the
    # free one that is actually used.
    assert len(exists_calls) == collisions + 1

    colliding_names = [c["branch"] for c in exists_calls[:collisions]]
    free_name = exists_calls[collisions]["branch"]

    # The service created the branch using the name reported as free ...
    assert create_call["new_branch"] == free_name
    # ... and NEVER issued a create against a name the provider reported as existing.
    assert create_call["new_branch"] not in colliding_names

    # The proposal branch differs from the protected target branch it is based on.
    assert create_call["new_branch"] != _BRANCH
