#!/usr/bin/env python3
"""Property-based test for fail-closed credential retrieval (`connector.service.propose_change`).

Covers Correctness Property 9 from the source-control-connector design: for *any* proposal
request in which credential retrieval from AWS Secrets Manager fails or does not complete
(``get_secret`` raises an exception, or returns ``None`` / an empty string), the connector
SHALL fail closed:

- it creates or modifies **no** proposal branch or proposal (the ``FakeProvider`` records
  **zero** operations of any kind — the credential gate runs before every provider op),
- it records a credential-retrieval-error audit entry, and
- it returns an error result and **never** reports success (no pull-request id/url).

The service is exercised with a ``FakeProvider`` injected via ``provider=`` and a
purpose-built enabled :class:`ConnectorConfig` injected via ``config=``. An authorized user is
placed in the request context and valid CloudFormation is proposed against an
allowlist-matching repository/branch, so the pipeline reaches the credential gate for every
example; the only varied element is the credential-retrieval failure mode, generated by
Hypothesis (varied raised exceptions, ``None``, and ``""``).

Validates: Requirements 4.6
"""

# Standard library
from unittest import mock

# Third-party packages
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

# Local modules
from connector.config import AllowlistEntry, ConnectorConfig
from connector.models import ProposedFile
from connector import service
from connector.service import propose_change
from support.fake_provider import FakeProvider
from utils.request_context import reset_request_context, set_request_context

pytestmark = pytest.mark.unit


# --- Fixed, valid request context ------------------------------------------
#
# A single allowlist entry the request matches exactly, so the allowlist gate passes and the
# pipeline advances to the credential gate under test.
_REPO = "org/iac-repo"
_BRANCH = "main"
_GROUP = "scm-writers"

# An authenticated user in an authorized group so the authorization gate passes. Identity is
# derived strictly from the request context, never from tool/model input.
_AUTHORIZED_CONTEXT = {"user_id": "user-9", "groups": [_GROUP], "session_id": "sess-9"}

# A benign, injection-free intent/title/description that clears input validation and
# prompt-injection detection so every request reaches the credential gate.
_INTENT = "update the storage bucket configuration for the service stack"
_TITLE = "Update service stack configuration"
_DESCRIPTION = "Adjust the configured storage bucket in the infrastructure template."

# Structurally valid CloudFormation so, absent the credential failure, IaC validation would
# pass — proving the request fails *only* because of the credential-retrieval failure.
_VALID_CFN = "Resources:\n  MyBucket:\n    Type: AWS::S3::Bucket\n"

# The provider operations that would constitute any read or write against source control.
_ALL_OPS = (
    "get_file",
    "get_files",
    "branch_exists",
    "latest_commit_sha",
    "create_branch",
    "commit_files",
    "open_change_proposal",
)


def _make_config() -> ConnectorConfig:
    """Build an enabled ConnectorConfig backed by a single allowlist entry."""
    return ConnectorConfig(
        enabled=True,
        provider="github",
        credential_secret_id="scm/credential",
        allowlist=(AllowlistEntry(repo=_REPO, target_branches=(_BRANCH,)),),
        authorized_groups=(_GROUP,),
        rate_limit_max=1000,
        rate_limit_window_seconds=3600,
        provider_timeout_seconds=30,
        retry_max_attempts=3,
        max_files_per_request=20,
        provider_base_url=None,
        audit_log_group="scm-audit",
        config_errors=(),
    )


def _proposed_files() -> list[ProposedFile]:
    """A single valid CloudFormation file to propose."""
    return [ProposedFile(path="template.yaml", content=_VALID_CFN, iac_format="cloudformation")]


# --- Credential-failure strategy -------------------------------------------


@st.composite
def _credential_failures(draw):
    """Generate a varied credential-retrieval failure mode for ``get_secret``.

    Yields a ``(kind, payload)`` pair where ``kind`` is:

    - ``"raises"`` → ``payload`` is an exception instance ``get_secret`` should raise
      (covers Secrets Manager errors, timeouts, network failures, and any other exception),
    - ``"returns"`` → ``payload`` is a falsy return value (``None`` or ``""``) that the
      fail-closed gate must treat as a retrieval failure.
    """
    kind = draw(st.sampled_from(["raises", "none", "empty"]))
    if kind == "none":
        return ("returns", None)
    if kind == "empty":
        return ("returns", "")

    exc_type = draw(
        st.sampled_from(
            [
                RuntimeError,
                TimeoutError,
                ConnectionError,
                ValueError,
                KeyError,
                OSError,
                Exception,
            ]
        )
    )
    message = draw(st.text(alphabet=st.characters(min_codepoint=32, max_codepoint=126), max_size=40))
    return ("raises", exc_type(message))


# --- Property 9 ------------------------------------------------------------


# Feature: source-control-connector, Property 9: Credential-retrieval failure is fail-closed
@settings(max_examples=100)
@given(failure=_credential_failures())
def test_property9_credential_retrieval_failure_is_fail_closed(failure):
    """Any credential-retrieval failure → no branch/commit/PR, an audit entry, an error result.

    For every generated failure mode (``get_secret`` raising an exception, or returning
    ``None`` / ``""``), ``propose_change`` performs no source-control operation whatsoever,
    records a credential-retrieval-error audit entry, and returns an error result that never
    reports a created proposal (Req 4.6).
    """
    kind, payload = failure
    fake = FakeProvider()

    if kind == "raises":
        get_secret_patch = mock.patch.object(service, "get_secret", side_effect=payload)
    else:
        get_secret_patch = mock.patch.object(service, "get_secret", return_value=payload)

    token = set_request_context(dict(_AUTHORIZED_CONTEXT))
    try:
        with (
            get_secret_patch as mock_get_secret,
            mock.patch.object(service, "logger") as mock_logger,
        ):
            result = propose_change(
                intent=_INTENT,
                files=_proposed_files(),
                iac_format="cloudformation",
                title=_TITLE,
                description=_DESCRIPTION,
                repository=_REPO,
                target_branch=_BRANCH,
                config=_make_config(),
                provider=fake,
            )
    finally:
        reset_request_context(token)

    # The pipeline actually reached the credential gate (proving the failure is what stopped
    # it, not an earlier gate).
    assert mock_get_secret.called

    # An error result is returned and no successful proposal is reported (Req 4.6).
    assert result.status == "error"
    assert result.status != "created"
    assert result.proposal_id is None
    assert result.proposal_url is None

    # ZERO provider operations of any kind were issued — no branch, commit, or PR was created
    # or modified (the credential gate runs before every provider op).
    assert fake.calls == []
    for op in _ALL_OPS:
        assert fake.calls_for(op) == [], f"credential failure unexpectedly invoked {op}"
    assert fake.created_branches == []
    assert fake.commits == []
    assert fake.pull_requests == []

    # A credential-retrieval-error audit entry was recorded (Req 4.6).
    assert mock_logger.error.called
    credential_error_calls = [
        call
        for call in mock_logger.error.call_args_list
        if call.kwargs.get("event") == "scm_credential_error"
        and call.kwargs.get("reason") == "credential_retrieval_failed"
    ]
    assert credential_error_calls, "expected a scm_credential_error audit entry"
    audit = credential_error_calls[0].kwargs
    assert audit.get("requesting_user") == _AUTHORIZED_CONTEXT["user_id"]
    assert audit.get("outcome") == "error"
