#!/usr/bin/env python3
"""Property-based test for proposal-branch determinism and base-commit selection.

Covers the v2 idempotency reshape (design Component 6 / Property V6): the proposal branch
the Connector creates is (a) *based on the verified source snapshot* (the ``base_revision``
the caller read, re-verified against the current target head) and (b) *deterministically
named* — its name is a pure function of the stable idempotency key, so the SAME logical
proposal always maps to the SAME branch. The old random-token + regeneration-loop scheme is
gone: there is no ``secrets.token_hex`` suffix, no timestamp, and no
``branch_exists``-collision retry loop.

``connector.service.propose_change`` runs its fail-closed pipeline and, on the provider
stage, reads ``latest_commit_sha`` for the matched target branch, verifies the caller's
``base_revision`` still matches it, derives a stable idempotency key from the request +
snapshot, and creates the proposal branch from that verified revision using the deterministic
name derived from the key.

Two facets are proven across generated inputs:

- **Base commit (read-before-write):** ``create_branch`` is called with ``from_sha`` equal to
  the exact verified head SHA the provider reported for the target branch (which also equals
  the ``base_revision`` the caller passed). Different SHAs are generated by Hypothesis.
- **Deterministic name:** ``create_branch`` is called exactly once with a ``gbaw/``-prefixed
  name that is distinct from the protected target branch, and re-running the SAME logical
  proposal (same repo/branch/base_revision/files/user/intent) against a fresh provider yields
  the SAME branch name — proving the name is a deterministic function of the request, not a
  random value.

The service is exercised with a ``FakeProvider`` injected via ``provider=`` and an enabled
:class:`SourceControlConfig` injected via ``config=``. An authorized user is placed in the
request context, valid CloudFormation is proposed against an allowlist-matching repo/branch,
and the rate-limit gate (which sits before the provider stage) is neutralized so this test
isolates the branch-selection behavior. The request context is reset per example.

Validates: Requirements 7.1, 7.2, 8.1, 8.2
"""

# Standard library
from unittest import mock

# Third-party packages
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

# Local modules
from connector import service
from connector.config import AllowlistEntry, SourceControlConfig
from connector.models import ProposedFile
from connector.service import propose_change
from support.config_factory import make_source_control_config
from support.fake_provider import FakeProvider
from utils.request_context import reset_request_context, set_request_context

pytestmark = pytest.mark.unit


# The single configured repository/branch the propose path defaults to (allowlist[0]);
# the request supplies no repo/branch so an authorized request lands an exact allowlist
# match and reaches the provider stage where the branch is selected and created.
_REPO = "org/iac-repo"
_BRANCH = "main"

# An authorized requesting user whose group intersects the configured authorized groups.
_AUTHORIZED_CONTEXT = {"user_id": "user-123", "groups": ["scm-writers"], "session_id": "s-1"}

# A structurally valid CloudFormation template (passes the IaC validation gate).
_VALID_CFN = '{"Resources": {"Bucket": {"Type": "AWS::S3::Bucket"}}}'

# A fixed logical proposal (intent/title/description) so re-runs share the same idempotency
# key and therefore the same deterministic branch name.
_INTENT = "update the storage bucket configuration"
_TITLE = "Update bucket configuration"
_DESCRIPTION = "Enable versioning on the storage bucket."


def _make_config() -> SourceControlConfig:
    """Build an enabled SourceControlConfig backed by a single-entry allowlist."""
    return make_source_control_config(
        enabled=True,
        provider="github",
        credential_secret_id="scm/credential",
        allowlist=(AllowlistEntry(repo=_REPO, target_branches=(_BRANCH,)),),
        authorized_groups=("scm-writers",),
        rate_limit_max=1000,
        rate_limit_window_seconds=3600,
        provider_timeout_seconds=30,
        retry_max_attempts=3,
        max_files_per_request=20,
        provider_base_url=None,
        audit_log_group="scm-audit",
        config_errors=(),
    )


def _proposed_files() -> list[ProposedFile]:
    return [ProposedFile(path="template.yaml", content=_VALID_CFN, iac_format="cloudformation")]


def _call_propose(fake: FakeProvider, base_revision: str):
    """Invoke ``propose_change`` with an authorized user; rate-limit neutralized.

    ``base_revision`` is the Verified_Source_Snapshot the caller "read"; the provider is
    programmed to report the same SHA as the current target head, so the read-before-write
    check passes and the branch-selection behavior under test is isolated.
    """
    token = set_request_context(dict(_AUTHORIZED_CONTEXT))
    try:
        with (mock.patch.object(service, "check_rate_limit", return_value=None),):
            return propose_change(
                intent=_INTENT,
                files=_proposed_files(),
                iac_format="cloudformation",
                title=_TITLE,
                description=_DESCRIPTION,
                base_revision=base_revision,
                config=_make_config(),
                provider=fake,
            )
    finally:
        reset_request_context(token)


# Feature: source-control-connector-v2, Property V6: proposal branch is deterministic and based on the verified snapshot
@settings(max_examples=100)
@given(
    latest_sha=st.from_regex(r"[0-9a-f]{7,40}", fullmatch=True),
)
def test_proposal_branch_deterministic_and_based_on_verified_snapshot(latest_sha):
    """The proposal branch is created from the verified snapshot revision and is
    deterministically named — the same logical proposal always maps to the same branch,
    with no random token or uniqueness-regeneration loop (Req 7.1, 7.2, 8.1, 8.2)."""
    fake = FakeProvider()

    # The provider reports this as the latest commit of the target branch; the caller read it
    # as the Verified_Source_Snapshot and passes it back as ``base_revision``, so the
    # read-before-write check passes and the proposal branch must be based on exactly this SHA.
    fake.set_return("latest_commit_sha", latest_sha)

    result = _call_propose(fake, base_revision=latest_sha)

    # The pipeline reached and completed the provider stage: exactly one proposal created.
    assert result.status == "created", result.message
    assert result.proposal_id is not None

    # --- base commit (read-before-write) ------------------------------------------------
    base_calls = fake.calls_for("latest_commit_sha")
    assert base_calls, "the service must read the latest commit of the target branch"
    assert base_calls[0]["repo"] == _REPO
    assert base_calls[0]["branch"] == _BRANCH

    create_calls = fake.calls_for("create_branch")
    assert len(create_calls) == 1, "exactly one branch must be created"
    create_call = create_calls[0]
    # The branch is created from the exact verified head SHA (== base_revision) (Req 7.1).
    assert create_call["from_sha"] == latest_sha
    assert create_call["repo"] == _REPO

    # --- deterministic name -------------------------------------------------------------
    branch_name = create_call["new_branch"]
    # A stable, provider-neutral prefix and no random token/timestamp.
    assert branch_name.startswith("gbaw/")
    # The proposal branch differs from the protected target branch it is based on.
    assert branch_name != _BRANCH

    # Determinism: re-running the SAME logical proposal against a FRESH provider produces the
    # SAME branch name (a pure function of the stable idempotency key), so a retry never
    # forks a second branch (Req 8.1, 8.2).
    fake2 = FakeProvider()
    fake2.set_return("latest_commit_sha", latest_sha)
    result2 = _call_propose(fake2, base_revision=latest_sha)
    assert result2.status == "created", result2.message
    rerun_create = fake2.calls_for("create_branch")
    assert len(rerun_create) == 1
    assert (
        rerun_create[0]["new_branch"] == branch_name
    ), "the same logical proposal must map to the same deterministic branch name"
