#!/bin/bash
set -e

# Scan Game Agent dependencies for known vulnerabilities
# Uses Grype (https://github.com/anchore/grype) against SBOMs generated by generate-sbom.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SBOM_DIR="$PROJECT_ROOT/sbom"

echo "🔍 Vulnerability Scan - Game Agent"
echo "========================================="

# Check for Grype
if ! command -v grype &> /dev/null; then
    echo "❌ Grype not found."
    echo ""
    echo "Install Grype:"
    echo "  macOS:  brew install grype"
    echo "  Linux:  curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin"
    echo ""
    echo "More info: https://github.com/anchore/grype#installation"
    exit 1
fi

# Generate SBOMs if they don't exist
BACKEND_SBOM="$SBOM_DIR/backend-sbom-latest.spdx.json"
FRONTEND_SBOM="$SBOM_DIR/frontend-sbom-latest.spdx.json"

if [ ! -f "$BACKEND_SBOM" ] || [ ! -f "$FRONTEND_SBOM" ]; then
    echo "📦 SBOMs not found, generating..."
    bash "$SCRIPT_DIR/generate-sbom.sh" "$@"
    echo ""
fi

# Severity threshold (default: medium)
FAIL_ON="${FAIL_ON:-medium}"
EXIT_CODE=0

# Scan backend
echo ""
echo "🔍 Scanning backend dependencies..."
echo "-----------------------------------"
if [ -f "$BACKEND_SBOM" ]; then
    grype "sbom:$BACKEND_SBOM" --fail-on "$FAIL_ON" 2>&1 || EXIT_CODE=$?
else
    echo "⚠️  Backend SBOM not found, skipping"
fi

# Scan frontend
echo ""
echo "🔍 Scanning frontend dependencies..."
echo "------------------------------------"
if [ -f "$FRONTEND_SBOM" ]; then
    grype "sbom:$FRONTEND_SBOM" --fail-on "$FAIL_ON" 2>&1 || EXIT_CODE=$?
else
    echo "⚠️  Frontend SBOM not found, skipping"
fi

echo ""
echo "========================================="
if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ Vulnerabilities found at or above '$FAIL_ON' severity"
    echo "   Review findings above and update dependencies as needed"
    echo ""
    echo "   Suppress false positives: grype sbom:<file> --fail-on <severity>"
    echo "   Override threshold: FAIL_ON=high ./scripts/scan-vulnerabilities.sh"
else
    echo "✅ No vulnerabilities found at or above '$FAIL_ON' severity"
fi

exit $EXIT_CODE
